project:
  type: website

website: 
  page-navigation: true
  title: "Python for Computational Chemistry"
  site-url: "insert site url here" 
  repo-url: insert github url here
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Website created by Navi, 2025"
    
  sidebar:
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Quarto website tutorial"       
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: outline_checklist.md
        text: Table of Contents
      - section: Algebra
        contents: 
          - href: Notebooks\01.Linear_Systems_concepts.ipynb
            text: Linear Systems Concepts
          - href: Notebooks\2.Computational_approaches_to_linear_systems.ipynb
            text: Computational approaches to Linear Systems       



format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true
