name: Auto-Add Completion Date

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Auto-update Completion Dates
        run: |
          python3 <<EOF
import re
from datetime import datetime

# Read README
with open('README.md', 'r') as f:
    lines = f.readlines()

updated = False
new_lines = []

for line in lines:
    # Match lines with ✅ Completed and empty Date Finished
    if re.search(r'\| ✅ Completed \|.*\|\s*\|\s*$', line):
        # Add current date
        today = datetime.today().strftime('%Y-%m-%d')
        line = re.sub(r'\|\s*\|\s*$', f'| {today} |\n', line)
        updated = True
    new_lines.append(line)

# Write back if any changes
if updated:
    with open('README.md', 'w') as f:
        f.writelines(new_lines)
else:
    print("No updates needed.")

EOF

      - name: Commit and Push if Changed
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Auto-add completion dates"
            git push
          else
            echo "No changes to commit."
          fi
